# Generated by Django 4.2 on 2023-08-07 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tweeter_id', models.CharField(max_length=200)),
                ('images_sentiments', models.CharField(blank=True, default='', max_length=200)),
                ('tweets_sentiments', models.CharField(blank=True, default='', max_length=200)),
                ('friends_sentiments', models.CharField(blank=True, default='', max_length=200)),
                ('images_distance', models.CharField(blank=True, default='', max_length=200)),
                ('tweets_distance', models.CharField(blank=True, default='', max_length=200)),
                ('images_topics', models.CharField(blank=True, default='', max_length=200)),
                ('tweets_topics', models.CharField(blank=True, default='', max_length=200)),
            ],
        ),
    ]
